Add names for base instructions
ThinkOpenly/sail-riscv pull request #37
Opened 2024-07-23 09:39 UTC by Linda-Njau

2024-07-23 14:02 UTC, ThinkOpenly requested changes
Thanks! There is a lot of subjectivity here, and the source manual is sometimes inconsistent, so I get to do it my way! ;-)
In general:
- all lower case
- try to treat the mnemonic as an initialism, such that each letter turns directly into a word starting with that letter
- keep the primary action as the first word if there is a choice

For "sla", "shift left arithmetic" is preferred over "arithmetic left shift", for example.

2024-07-24 11:19 UTC, Linda-Njau commented
Changed and squashed.

2024-07-24 12:46 UTC, ThinkOpenly commented on model/riscv_insts_base.sail
> +  $[name "bitwise logical operation"]
This one ended up as "exclusive XOR", rather than the preferred "exclusive OR".

2024-07-24 12:47 UTC, ThinkOpenly requested changes

2024-07-24 12:47 UTC, ThinkOpenly commented on model/riscv_insts_base.sail
> +  $[name "exclusive XOR"]
"exclusive OR" :-)

2024-07-24 13:42 UTC, Linda-Njau commented on model/riscv_insts_base.sail
> +  $[name "exclusive XOR"]
oops.
Fixed and squashed : )

2024-07-24 13:57 UTC, ThinkOpenly approved these changes

2024-08-01 02:25 UTC, ThinkOpenly commented on model/riscv_insts_cdext.sail
> +$[name "compressed floating-point load double-precision from stack pointer"]
Let's put the action word first: load
Then the target: double-precision floating-point
Then the action modifier: from stack pointer
Then the "class": (compressed)
So, "load double-precision floating point from stack pointer (compressed)".

Similarly for the others in this commit, please. Thanks!

2024-08-05 18:10 UTC, ThinkOpenly approved these changes

2024-08-06 17:16 UTC, Linda-Njau commented
I've updated the names to lowercase as we discussed.

2024-08-07 17:51 UTC, merged