Make extension discriminator clear
ThinkOpenly/sail-riscv pull request #8
Opened 2024-01-19 15:25 UTC by Bakugo90

Implement #4
For this pull request i work on "A" and "M" extension. 
I've cloned your JSON branch and worked from that so I can continue what you've already done.

> I have already implemented all of the necessary changes. Look at the "JSON" branch in this repository. Further work here should probably be on top of that branch.
Of course, I've noticed that you've already worked on the "V" and "Zbkb" extension. And that really helped me to recognise the "M" and "A" extensions.

2024-01-19 17:06 UTC, ThinkOpenly commented
Greetings, and thanks for this submission!

While the changes you have implemented are not incorrect, they do not address the issue described in #4.

If you look at most of the changes in the existing code where the `extension` function is used, you'll see it mostly is appended to (one or both sides of) `mapping clause encdec` definitions. Issue #4 is asking that the same type of conditional expressions used for some extensions be used for _all_ extensions. For example, the current code has:
```
mapping clause encdec = LOADRES(aq, rl, rs1, size, rd) if amo_width_valid(size)
```
and it would need to be something like:
```
mapping clause encdec = LOADRES(aq, rl, rs1, size, rd) if extension("A") & amo_width_valid(size)
```

2024-03-06 20:04 UTC, ThinkOpenly requested changes
A few issues to fix. If you want to fix this up and resubmit, that would be ideal. If you prefer that I fix them up and merge, let me know.

2024-03-06 20:04 UTC, ThinkOpenly commented on model/riscv_insts_mext.sail
> +mapping clause encdec = REM(rs2, rs1, rd, s) & extension("M")
The `&` should be `if`.

2024-03-06 20:04 UTC, ThinkOpenly commented on model/riscv_insts_mext.sail
>        if sizeof(xlen) == 64
This doesn't compile. You need to combine the new condition with the existing condition, and on both sides of the mapping, like this:
```
mapping clause encdec = MULW(rs2, rs1, rd)
      if extension("M") & sizeof(xlen) == 64
  <-> 0b0000001 @ rs2 @ rs1 @ 0b000 @ rd @ 0b0111011
      if extension("M") & sizeof(xlen) == 64
```

2024-03-06 20:04 UTC, ThinkOpenly commented on model/riscv_insts_mext.sail
> +mapping clause encdec = DIVW(rs2, rs1, rd, s) if extension("M")
same as previous comment.

2024-03-06 20:04 UTC, ThinkOpenly commented on model/riscv_insts_mext.sail
> +mapping clause encdec = REMW(rs2, rs1, rd, s) if extension("M")
same as previous comment.

2024-03-07 16:40 UTC, Bakugo90 commented
Done ! @ThinkOpenly

2024-03-07 17:53 UTC, ThinkOpenly approved these changes

2024-03-07 18:00 UTC, merged

2024-08-06 16:06 UTC, ThinkOpenly commented
FYI, this commit and other related "extension tagging" commits have been merged upstream. https://github.com/riscv/sail-riscv/commit/ebf57cc79459bdba3e8d15e84941b6dcd088f5f4. Congratulations, and thank you for your efforts! :tada: